#(C) Carlos A. R. de Souza. Distributable under the ISC license.
namespace eval ::ttk::dialog::file {  
	::msgcat::mcset pt_BR Ok Ok
	::msgcat::mcset pt_BR Cancel Cancelar 
	::msgcat::mcset pt_BR Open Abrir
    ::msgcat::mcset pt_BR Location Localização
    ::msgcat::mcset pt_BR Filter Filtro
    ::msgcat::mcset pt_BR Name Nome
    ::msgcat::mcset pt_BR Size Tamanho
    ::msgcat::mcset pt_BR Date Data
    ::msgcat::mcset pt_BR Permissions Permissões
    ::msgcat::mcset pt_BR Owner Dono
    ::msgcat::mcset pt_BR Group Grupo 
    ::msgcat::mcset pt_BR Folder Pasta
    ::msgcat::mcset pt_BR Sorting Filtragem
    ::msgcat::mcset pt_BR Reverse {Ao contrário}
    
    ::msgcat::mcset pt_BR {Short View} {Visão resumida}
    ::msgcat::mcset pt_BR {Detailed View} {Visão detalhada}
    ::msgcat::mcset pt_BR {Show Hidden Files} {Mostrar arquivos ocultos}
    ::msgcat::mcset pt_BR {Separate Folders} {Separar pastas}
    ::msgcat::mcset pt_BR {By Name} {Por nome}
    ::msgcat::mcset pt_BR {By Date} {Por data}
    ::msgcat::mcset pt_BR {By Size} {Por tamanho}
    ::msgcat::mcset pt_BR {Folders First} {Pastas primeiro}
    ::msgcat::mcset pt_BR {New Folder} {Nova pasta} 
    ::msgcat::mcset pt_BR {Create new folder in} {Criar nova pasta em...}
    
    ::msgcat::mcset pt_BR {File "%s" already exists. Do you want to overwrite it?} \
    {O arquivo "%s" já existe. Deseja sobreescrevê-lo?}
    
    ::msgcat::mcset pt_BR {File "%s" does not exist.} {O arquivo "%s" não existe}
  
    ::msgcat::mcset pt_BR {Cannot change to the directory "%s". Permission denied.} \
    {Não é possível visualizar a pasta "%s". Permissão negada.}
}


