#!/bin/bash
# Functioned-out - may be useful later.
proc_path()
{
    PATH="$(perl -lE 'my @p = split/:/,$ENV{PATH}; print join q#:#, grep { ! m#\A/opt/python# } @p;')" "$@"
}
make test || exit -1
make dist || exit -1
tar -xvf dist/PySolFC-*.tar.xz || exit -1
(cd PySolFC-*/ && make test) || exit -1

if [ "$TRAVIS_OS_NAME" = "osx" ]; then
    PYTHONPATH="$PYTHONPATH:." python3 setup_osx.py py2app
    (cd dist && tar cJf ../PySolFC.app.tar.xz PySolFC.app/)
fi
